### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by ghost** [CoderDojoLuzern/CoderDojoLuzern.github.io#10]
Hey guys,

I am writing as a subject for helping you. I follow you guys and wish you success! I know a lot about compiler construction especially in Lua, Elixir, Ocaml, Elm and Crystal. So if you’d like to need some resources about some advanced stuff for the Coderdojo, just contact me :)

Best regards
Timo S.

PS it’s me... the guy with the compilers :)

**Comment by meshell** [comment]
Thanks a lot for your support. 
See you soon
best regards
