### ISSUE TITLE
Unity Anleitung anpassen

### ISSUE THREAD

**Issue by jonathanwinter123** [CoderDojoLuzern/CoderDojoLuzern.github.io#5]
Am Anfang der Anleitung steht, man soll ein Package importieren, welches nicht auffindbar ist.
Wahrscheinlich muss die Anleitung aktualisiert werden oder man benutzt direkt die Tutorials von Unity.

**Comment by meshell** [comment]
Habe die Anleitung entfernt (von der Info Seite) und auf die Englischen Tutorials verwiesen.
